export const ROUTE_NAMES = Object.freeze({
  HOME: 'home',
  MATH_HUB: 'math-hub',
  MATH_MULTIPLICATIONS: 'math-multiplications',
  MATH_SYMMETRY: 'math-symmetry',
  LANGUAGES_HUB: 'languages-hub',
  LANGUAGES_ENGLISH: 'languages-english',
  LANGUAGES_FRENCH: 'languages-french',
  LANGUAGES_FRENCH_TABLE: 'languages-french-table',
  LANGUAGES_FRENCH_FLASHCARDS: 'languages-french-flashcards',
  LANGUAGES_FRENCH_QCM: 'languages-french-qcm',
  LANGUAGES_FRENCH_INPUT: 'languages-french-input',
  STUDIO_OPS_LOGIN: 'studio-ops-login',
  STUDIO_OPS_PANEL: 'studio-ops-panel',
  STUDIO_OPS_HELP: 'studio-ops-help',
  LEGAL_NOTICE: 'legal-notice',
  LEGAL_PRIVACY: 'legal-privacy',
  LEGAL_TERMS: 'legal-terms',
  LEGAL_COOKIES: 'legal-cookies',
});

export const ROUTE_PATHS = Object.freeze({
  HOME: '/',
  MATH_HUB: '/math',
  MATH_MULTIPLICATIONS: '/math/multiplications',
  MATH_SYMMETRY: '/math/symmetry',
  LANGUAGES_HUB: '/languages',
  LANGUAGES_ENGLISH: '/languages/english',
  LANGUAGES_FRENCH: '/languages/french',
  LANGUAGES_FRENCH_TABLE: '/languages/french/table/:verbKey',
  LANGUAGES_FRENCH_FLASHCARDS: '/languages/french/flashcards/:verbKey',
  LANGUAGES_FRENCH_QCM: '/languages/french/qcm/:verbKey',
  LANGUAGES_FRENCH_INPUT: '/languages/french/input/:verbKey',
  STUDIO_OPS_LOGIN: '/-/studio-ops',
  STUDIO_OPS_PANEL: '/-/studio-ops/panel',
  STUDIO_OPS_HELP: '/-/studio-ops/help',
  LEGAL_NOTICE: '/legal/legal-notice',
  LEGAL_PRIVACY: '/legal/privacy-policy',
  LEGAL_TERMS: '/legal/terms-of-use',
  LEGAL_COOKIES: '/legal/cookie-policy',
});
